version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6391:5000"
    restart: unless-stopped
    container_name: youtube-transcript-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/transcript?videoId=dQw4w9WgXcQ"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M 